apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/neural-cortex-424806-r2/notifications/production
        name: notifications
        env:
          - name: PORT
            value: '4004'
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: mailconfig
                key: smtpUser
          - name: MAIL_HOST
            valueFrom:
              secretKeyRef:
                name: mailconfig
                key: mailHost
          - name: MAIL_PORT
            valueFrom:
              secretKeyRef:
                name: mailconfig
                key: mailPort
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mailconfig
                key: mailUsername
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mailconfig
                key: mailPassword
        ports:
            - containerPort: 4004
