apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - name: "4004"
    port: 4004
    protocol: TCP
    targetPort: 4004
  selector:
    app: notifications
  type: ClusterIP
