apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  ports:
  - name: "4003"
    port: 4003
    protocol: TCP
    targetPort: 4003
  selector:
    app: payments
  type: ClusterIP
