apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
  - name: "4001"
    port: 4001
    protocol: TCP
    targetPort: 4001
  - name: "4002"
    port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    app: auth
  type: ClusterIP
