apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  ports:
  - name: 'http'
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: reservations
  type: NodePort
